project:
  type: book
  output-dir: docs
  pre-render: 
    - R/start_caption_index.R
  post-render: 
    - R/fix_style.R

quarto-required: 1.4.553

book:
  version: 1.1.0
  title: "Twin Cities MSA Greenhouse Gas Inventory"
  subtitle: "Climate Pollution Reduction Grant Documentation"
  author: "Metropolitan Council"
  date: today
  page-navigation: true
  search: true
  repo-url: https://github.com/Metropolitan-Council/ghg-cprg
  repo-actions: source
  reader-mode: true
  sidebar:
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 2
    # footer: "*On request, this publication will be made available in alternative formats to people with disabilities. Call Metropolitan Council information at 651-602-1140 or TTY 651-291-0904.*"
  chapters:
    - index.qmd
    - part: "Energy"
      chapters:
       - _energy/_energy.qmd
       - _energy/data_electricity.qmd
       - _energy/data_natural_gas.qmd
       - _energy/data_propane_kerosene.qmd
       # - _energy/data_energy.qmd
       # - _energy/pa_energy.qmd
       - _energy/qc_energy.qmd

    - part: "Transportation"
      chapters:
       - _transportation/_transportation.qmd
       - _transportation/data_transportation.qmd
       # - _transportation/pa_transportation.qmd
       - _transportation/qc_transportation.qmd
       
    - part: "Waste and Wastewater"
      chapters:
       - _waste/_waste.qmd
       - _waste/data_waste.qmd
       # - _waste/pa_waste.qmd
       - _waste/qc_waste.qmd
       - _waste/qc_waste_other.qmd
    
    - part: "Natural Systems"
      chapters:
       - _nature/_natural_systems.qmd
       - _nature/data_land_area_sequestration.qmd
       
  appendices:
    # - _meta/data_request_template.qmd
    - _meta/supplementary_data.qmd
    - _meta/supplementary_tables.qmd
    - _meta/additional_resources.qmd
    - _energy/utility_service_area_maps.qmd
    - _meta/lidac_maps.qmd
    - figures.qmd
    - tables.qmd
    - references.qmd

bibliography: metcouncil-cprg-ghg.bib
csl: assets/chicago-author-date.csl
citeproc: true
# zotero: "metcouncil-cprg-ghg"

link-external-newwindow: true
link-external-icon: true 
template: style/council-template.html
resources: 
      - style/standalone_footer.html
      - style/standalone_header.html
      - style/footer-logo.png
      - style/main-logo.png
      - style/standalone_header_footer.css

crossref: 
  ref-hyperlink: true
  chapters: true
  appendix-title: "Appendix"
      
execute:
 echo: false
 code-overflow: wrap

format: 
  html:
    theme: [cosmo, style/council.scss, style/font.scss] 
    toc: true
    self-contained: false
    grid: 
      content-mode: full
      margin-width: 100px
    toc-depth: 3
    number-sections: true
    # number-depth: 4
    copyright: "Metropolitan Council"
    fig-responsive: true
    link-external-filter: "metrocouncil.org|tel|metrotransit|metrocouncil.metctest.state.mn.us|github.com/Metropolitan-Council"
    fig-cap-location: top
    knitr: 
      opts_chunk: 
          echo: false
          message: false
          warning: false
          out-width: "95%"
          out-height: "60%"

filters:
  - assets/include-files.lua
  - quarto

