# Chapter title
```{r  include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.pos = "H",
  out.width = "100%",
  dpi = 300
)


knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
source(file.path(here::here(), "R/_quarto_helpers.R"))
source(file.path(here::here(), "R/_load_pkgs.R"))
hookaddcap()
```


```{r fig-figure}
#| fig-cap: "A figure"
#| out-width: "95%"
#| include: false
# all figure chunks should be named "fig-{plot-desc}"
shinipsum::random_ggplotly(type = "histogram") %>%
  councilR::plotly_layout(
    main_title = "Histogram"
  )
```

```{r tbl-table}
#| tbl-cap: "A table"
#| out-width: "95%"
#| include: false
shinipsum::random_table(nrow = 5, ncol = 3) %>%
  gt() %>%
  gt::opt_row_striping() %>%
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_column_labels()
  ) %>%
  gt::fmt_markdown() %>%
  gt::as_raw_html()
```

<!-- chapter content -->


```{r echo=FALSE}
caption_index <- readRDS(file.path(here::here(), "caption_index.RDS"))
caption_index <- as.character(as.numeric(caption_index) + 1) %>% stringr::str_pad(width = 2, side = "left", pad = "0")
saveCap(paste0("cap-", caption_index))
saveRDS(caption_index, file.path(here::here(), "caption_index.RDS"))
```

{{< pagebreak >}}
