# 02_compile_eia_wi_elec_activity.R
# ──────────────────────────────────────────────────────────────────────────────
# Compile a utility x year electricity activity table for WI in-scope utilities
# by downloading and parsing EIA-861 detail files across 2005–latest.
#
# Wisconsin electric cooperatives and municipals do not report to the state in
# the same way MN utilities do (via 7610). County-level deliveries are not
# published for  WI utilities, so EIA-861 is used as the base activity
# source. Downstream scripts allocate these utility x state totals to counties
# using customer-count / population weights.
#
# Inputs:
#   distinct_electricity_util_type_WI.RDS  — WI in-scope utility list
#   EIA-861 annual zip files               — downloaded from eia.gov
#     Sales_Ult_Cust  (long form: sector MWh, customer counts, revenues)
#     Short_Form      (short form: total MWh + customers only)
#
# Outputs:
#   WI_utility_elec_activity_eia861.RDS
#       utility_name, utility_name_raw, state, emissions_year,
#       residential, commercial, industrial, transportation, total,
#       residential_customers, commercial_customers, industrial_customers,
#       transportation_customers, total_customers,
#       unit_activity, data_source, eia_form
#
# data_source values:
#   "eia_861_long"   — from Sales_Ult_Cust (long form)
#   "eia_861_short"  — from Short_Form (short form; small utilities/coops)
# ──────────────────────────────────────────────────────────────────────────────

source("R/_load_pkgs.R")

# --- configuration -----------------------------------------------------------

backcast_start <- 2005L
latest_year <- 2025
full_year_range <- backcast_start:latest_year
state_abb <- "WI"

dir_eia_861 <- here("_energy", "data-raw", "eia_861")
dir.create(dir_eia_861, showWarnings = FALSE, recursive = TRUE)

# --- WI in-scope utilities ---------------------------------------------------
# Reuses the utility list generated by wisconsin_electricUtilities.R (which
# clips PSCW service-area shapefiles to St. Croix and Pierce counties).

wi_elec_utils_scope <- read_rds(here(
  "_energy", "data", "distinct_electricity_util_type_WI.RDS"
))
# drop any spatial attributes (file may be an sf object depending on how it was saved)
if (inherits(wi_elec_utils_scope, "sf")) {
  wi_elec_utils_scope <- sf::st_drop_geometry(wi_elec_utils_scope)
}
wi_elec_utils_scope <- distinct(wi_elec_utils_scope, utility_name, utility_type)

message(sprintf(
  "WI in-scope electric utilities: %d",
  n_distinct(wi_elec_utils_scope$utility_name)
))
print(wi_elec_utils_scope)

# --- name harmonization for EIA-861 names ------------------------------------
# EIA-861 utility names vary by year and often differ from PSCW LABEL values.
# Map all known variants to the canonical PSCW name so joins downstream work.

eia_name_lookup_wi <- c(
  # Northern States Power Co - Wisconsin (Xcel WI subsidiary)
  "Northern States Power Co - Wisconsin"       = "Northern States Power Company-Wisconsin",
  "Northern States Power Co-Wisconsin"          = "Northern States Power Company-Wisconsin",
  "Northern States Power Company - Wisconsin"   = "Northern States Power Company-Wisconsin",
  "Northern States Power Company-Wisconsin"     = "Northern States Power Company-Wisconsin",
  "Northern States Power Company (WIS)"         = "Northern States Power Company-Wisconsin",
  "Northern States Power Co (Wisconsin)"        = "Northern States Power Company-Wisconsin",
  # EIA-861 files for most years report NSP-WI under this bare name with no
  # state qualifier at all (safe to map directly since parsing already
  # restricts to state == "WI" rows before this harmonization step runs).
  "Northern States Power Co"                    = "Northern States Power Company-Wisconsin",

  # Dunn Energy Cooperative
  "Dunn Energy Cooperative"                     = "Dunn Energy Cooperative",
  "Dunn County Electric Coop"                   = "Dunn Energy Cooperative",
  "Dunn Energy Coop"                            = "Dunn Energy Cooperative",

  # Pierce-Pepin Electric Cooperative Services
  "Pierce-Pepin Cooperative Services"           = "Pierce-Pepin Electric Cooperative Services",
  "Pierce-Pepin Electric Cooperative Services"  = "Pierce-Pepin Electric Cooperative Services",
  "Pierce Pepin Cooperative Services"           = "Pierce-Pepin Electric Cooperative Services",
  "Pierce-Pepin Coop Services Inc"              = "Pierce-Pepin Electric Cooperative Services",
  "Pierce-Pepin Coop Services"                  = "Pierce-Pepin Electric Cooperative Services",

  # Polk-Burnett Electric Cooperative
  "Polk-Burnett Electric Coop"                  = "Polk-Burnett Electric Cooperative",
  "Polk-Burnett Electric Cooperative"           = "Polk-Burnett Electric Cooperative",
  "Polk Burnett Electric Cooperative"           = "Polk-Burnett Electric Cooperative",

  # St Croix Electric Cooperative
  "St. Croix Electric Coop"                     = "St Croix Electric Cooperative",
  "St Croix Electric Coop"                      = "St Croix Electric Cooperative",
  "St. Croix Electric Cooperative"              = "St Croix Electric Cooperative",
  "St Croix Electric Cooperative"               = "St Croix Electric Cooperative",

  # River Falls Municipal Utility
  "City of River Falls - (WI)"                  = "River Falls Municipal Utility",
  "River Falls Municipal Utility"               = "River Falls Municipal Utility",
  "River Falls Municipal Utilities"             = "River Falls Municipal Utility",
  "City of River Falls"                         = "River Falls Municipal Utility",

  # New Richmond Municipal Electric Utility
  "City of New Richmond - (WI)"                 = "New Richmond Municipal Electric Utility",
  "City of New Richmond"                        = "New Richmond Municipal Electric Utility",
  "New Richmond Utilities"                      = "New Richmond Municipal Electric Utility",
  "New Richmond Municipal Electric Utility"     = "New Richmond Municipal Electric Utility"
)

harmonize_eia_names_wi <- function(names) {
  # Case- and whitespace-insensitive match: EIA-861 raw names for the same
  # utility vary in capitalization across years (older "reformatted" 2005-2011
  # archives in particular are often ALL CAPS), so an exact-match lookup
  # silently misses years even when the name is otherwise a known variant.
  normalized <- toupper(trimws(names))
  lookup_keys <- toupper(trimws(names(eia_name_lookup_wi)))
  idx <- match(normalized, lookup_keys)
  ifelse(is.na(idx), names, unname(eia_name_lookup_wi[idx]))
}

# --- download EIA-861 zip files ----------------------------------------------

download_eia_861 <- function(years, dest_dir) {
  for (yr in years) {
    zip_file <- file.path(dest_dir, sprintf("f861%d.zip", yr))
    if (file.exists(zip_file)) next

    # URL pattern varies by year:
    #   latest       : .../eia861/zip/f861YYYY.zip
    #   2012-latest-1: .../eia861/archive/zip/f861YYYY.zip
    #   2005-2011    : .../eia861/archive/zip/861_YYYY.zip (reformatted)
    urls <- if (yr >= 2012) {
      c(
        sprintf("https://www.eia.gov/electricity/data/eia861/zip/f861%d.zip", yr),
        sprintf("https://www.eia.gov/electricity/data/eia861/archive/zip/f861%d.zip", yr)
      )
    } else {
      c(
        sprintf("https://www.eia.gov/electricity/data/eia861/archive/zip/861_%d.zip", yr),
        sprintf("https://www.eia.gov/electricity/data/eia861/archive/zip/f861%d.zip", yr)
      )
    }

    downloaded <- FALSE
    for (url in urls) {
      res <- tryCatch(
        {
          download.file(url, zip_file, mode = "wb", quiet = TRUE)
          TRUE
        },
        error = function(e) FALSE,
        warning = function(w) FALSE
      )
      if (isTRUE(res) && file.exists(zip_file) && file.info(zip_file)$size > 1024) {
        message(sprintf("  downloaded EIA-861 %d", yr))
        downloaded <- TRUE
        break
      } else if (file.exists(zip_file)) {
        file.remove(zip_file)
      }
    }
    if (!downloaded) warning(sprintf("Failed to download EIA-861 for %d", yr))
  }
}

# --- helpers to find and read files inside a zip -----------------------------

find_file_in_zip <- function(zip_file, patterns) {
  zip_contents <- unzip(zip_file, list = TRUE)$Name
  for (p in patterns) {
    hits <- grep(p, zip_contents, value = TRUE, ignore.case = TRUE)
    if (length(hits) > 0) {
      # prefer xlsx over xls over csv
      hits <- hits[order(!grepl("\\.xlsx$", hits, ignore.case = TRUE),
        !grepl("\\.xls$", hits, ignore.case = TRUE))]
      return(hits[1])
    }
  }
  NA_character_
}

read_eia_tabular <- function(zip_file, file_in_zip) {
  temp_dir <- tempdir()
  unzip(zip_file, files = file_in_zip, exdir = temp_dir, overwrite = TRUE)
  path <- file.path(temp_dir, file_in_zip)

  # Detect header row by scanning for a row that contains "Utility" and "State"
  detect_header_and_read <- function(reader_preview, reader_full) {
    preview <- tryCatch(reader_preview(), error = function(e) NULL)
    if (is.null(preview)) return(NULL)
    header_row <- NA_integer_
    for (r in seq_len(nrow(preview))) {
      row_vals <- toupper(as.character(unlist(preview[r, ])))
      if (any(grepl("UTILITY", row_vals)) && any(grepl("STATE", row_vals))) {
        header_row <- r
        break
      }
    }
    skip_n <- if (!is.na(header_row)) header_row - 1 else 0
    tryCatch(reader_full(skip_n), error = function(e) NULL)
  }

  if (grepl("\\.xlsx$|\\.xls$", file_in_zip, ignore.case = TRUE)) {
    raw <- detect_header_and_read(
      reader_preview = function() readxl::read_excel(path, col_names = FALSE, n_max = 10),
      reader_full = function(skip_n) readxl::read_excel(path, skip = skip_n, guess_max = 10000)
    )
  } else {
    raw <- detect_header_and_read(
      reader_preview = function() readr::read_csv(path, col_names = FALSE, n_max = 10, show_col_types = FALSE),
      reader_full = function(skip_n) readr::read_csv(path, skip = skip_n, show_col_types = FALSE, guess_max = 10000)
    )
  }

  if (is.null(raw) || nrow(raw) == 0) return(NULL)

  # Standardize column names
  names(raw) <- tolower(trimws(names(raw)))
  names(raw) <- gsub("[\\s._]+", "_", names(raw))
  names(raw) <- gsub("_+$", "", names(raw))
  raw
}

find_col <- function(col_names, patterns) {
  for (p in patterns) {
    hits <- grep(p, col_names, value = TRUE, ignore.case = TRUE)
    if (length(hits) > 0) return(hits[1])
  }
  NA_character_
}

safe_numeric <- function(x) suppressWarnings(as.numeric(as.character(x)))

# --- parse Sales to Ultimate Customers (long form) ---------------------------
# Long form provides sector MWh (residential/commercial/industrial/transport)
# and customer counts by sector.

parse_eia_861_long <- function(zip_file, year, state_abb) {
  file_in_zip <- find_file_in_zip(
    zip_file,
    patterns = c("sales_ult_cust", "sales_ult", "sales_to_ultimate")
  )
  if (is.na(file_in_zip)) return(tibble())

  raw <- read_eia_tabular(zip_file, file_in_zip)
  if (is.null(raw)) return(tibble())

  col_names <- names(raw)
  name_col <- find_col(col_names, c("^utility_name$", "utility.*name", "^utility$"))
  state_col <- find_col(col_names, c("^state$", "^_tate$", "tate$", "^st$"))
  if (is.na(name_col) || is.na(state_col)) return(tibble())

  # Sector MWh: positional if not clearly named. EIA convention across years:
  # residential, commercial, industrial, transportation, total (in that order)
  mwh_cols <- grep("megawatthour|megawatt.*hour|mwh|sales_.*mwh", col_names,
    value = TRUE, ignore.case = TRUE)
  cust_cols <- grep("^customer|customers?$|count", col_names,
    value = TRUE, ignore.case = TRUE)
  # narrow customers columns: EIA convention is res/com/ind/transp/total after
  # the sector MWh + revenue blocks. We'll just take the last 5 "customer" cols.
  cust_cols_positional <- tail(cust_cols, 5)

  res_col <- find_col(col_names, c("^residential$", "res.*megawatt", "res.*mwh"))
  com_col <- find_col(col_names, c("^commercial$", "comm.*megawatt", "com.*mwh"))
  ind_col <- find_col(col_names, c("^industrial$", "ind.*megawatt", "ind.*mwh"))
  trn_col <- find_col(col_names, c("^transportation$", "trans.*megawatt", "trans.*mwh"))
  tot_col <- find_col(col_names, c("^total$", "total.*megawatt", "total.*mwh"))

  if (is.na(res_col) && length(mwh_cols) >= 5) {
    res_col <- mwh_cols[1]; com_col <- mwh_cols[2]
    ind_col <- mwh_cols[3]; trn_col <- mwh_cols[4]
    tot_col <- mwh_cols[5]
  } else if (is.na(res_col) && length(mwh_cols) >= 4) {
    res_col <- mwh_cols[1]; com_col <- mwh_cols[2]
    ind_col <- mwh_cols[3]; tot_col <- mwh_cols[4]
  }

  # Filter to state
  state_hits <- which(toupper(as.character(raw[[state_col]])) == toupper(state_abb))
  if (length(state_hits) == 0) return(tibble())
  raw_st <- raw[state_hits, ]

  result <- tibble(
    utility_name_raw = as.character(raw_st[[name_col]]),
    state            = state_abb,
    emissions_year   = as.integer(year)
  )
  if (!is.na(res_col)) result$residential    <- safe_numeric(raw_st[[res_col]])
  if (!is.na(com_col)) result$commercial     <- safe_numeric(raw_st[[com_col]])
  if (!is.na(ind_col)) result$industrial     <- safe_numeric(raw_st[[ind_col]])
  if (!is.na(trn_col)) result$transportation <- safe_numeric(raw_st[[trn_col]])
  if (!is.na(tot_col)) result$total          <- safe_numeric(raw_st[[tot_col]])

  # Customer counts (positional fallback)
  if (length(cust_cols_positional) >= 5) {
    result$residential_customers    <- safe_numeric(raw_st[[cust_cols_positional[1]]])
    result$commercial_customers     <- safe_numeric(raw_st[[cust_cols_positional[2]]])
    result$industrial_customers     <- safe_numeric(raw_st[[cust_cols_positional[3]]])
    result$transportation_customers <- safe_numeric(raw_st[[cust_cols_positional[4]]])
    result$total_customers          <- safe_numeric(raw_st[[cust_cols_positional[5]]])
  } else if (length(cust_cols_positional) >= 4) {
    result$residential_customers <- safe_numeric(raw_st[[cust_cols_positional[1]]])
    result$commercial_customers  <- safe_numeric(raw_st[[cust_cols_positional[2]]])
    result$industrial_customers  <- safe_numeric(raw_st[[cust_cols_positional[3]]])
    result$total_customers       <- safe_numeric(raw_st[[cust_cols_positional[4]]])
  }

  # Compute total if missing but sectors are present
  sector_cols <- intersect(c("residential", "commercial", "industrial", "transportation"), names(result))
  if (!"total" %in% names(result) && length(sector_cols) >= 3) {
    result$total <- rowSums(result[, sector_cols], na.rm = TRUE)
  }

  result %>%
    mutate(
      utility_name  = harmonize_eia_names_wi(utility_name_raw),
      unit_activity = "MWh",
      data_source   = "eia_861_long",
      eia_form      = "EIA-861"
    ) %>%
    filter(!is.na(total), total > 0)
}

# --- parse Short Form (small utility survey; total only) ---------------------

parse_eia_861_short <- function(zip_file, year, state_abb) {
  file_in_zip <- find_file_in_zip(
    zip_file,
    patterns = c("short_form", "shortform", "^short", "^861s")
  )
  if (is.na(file_in_zip)) return(tibble())

  raw <- read_eia_tabular(zip_file, file_in_zip)
  if (is.null(raw)) return(tibble())

  col_names <- names(raw)
  name_col <- find_col(col_names, c("^utility_name$", "utility.*name", "^utility$"))
  state_col <- find_col(col_names, c("^state$", "^_tate$", "tate$", "^st$"))
  if (is.na(name_col) || is.na(state_col)) return(tibble())

  # Short form typically reports one MWh total + one customer total
  mwh_col <- find_col(col_names, c(
    "sales.*mwh", "megawatthour", "total.*mwh", "sold.*mwh", "^mwh$"
  ))
  cust_col <- find_col(col_names, c(
    "total.*customer", "customer.*total", "^customers?$", "^customer_count$"
  ))

  state_hits <- which(toupper(as.character(raw[[state_col]])) == toupper(state_abb))
  if (length(state_hits) == 0) return(tibble())
  raw_st <- raw[state_hits, ]

  result <- tibble(
    utility_name_raw = as.character(raw_st[[name_col]]),
    state            = state_abb,
    emissions_year   = as.integer(year),
    total            = if (!is.na(mwh_col)) safe_numeric(raw_st[[mwh_col]]) else NA_real_,
    total_customers  = if (!is.na(cust_col)) safe_numeric(raw_st[[cust_col]]) else NA_real_
  ) %>%
    mutate(
      utility_name  = harmonize_eia_names_wi(utility_name_raw),
      unit_activity = "MWh",
      data_source   = "eia_861_short",
      eia_form      = "EIA-861S"
    ) %>%
    filter(!is.na(total), total > 0)

  result
}

# ═════════════════════════════════════════════════════════════════════════════
# Run download + parse + assemble
# ═════════════════════════════════════════════════════════════════════════════

message("\n=== Downloading EIA-861 zip files ===")
download_eia_861(full_year_range, dir_eia_861)

message("\n=== Parsing EIA-861 long form (Sales_Ult_Cust) ===")
eia_long <- map_dfr(full_year_range, function(yr) {
  zip_file <- file.path(dir_eia_861, sprintf("f861%d.zip", yr))
  if (!file.exists(zip_file)) return(tibble())
  out <- tryCatch(
    parse_eia_861_long(zip_file, yr, state_abb),
    error = function(e) {
      warning(sprintf("Long-form parse failed for %d: %s", yr, e$message))
      tibble()
    }
  )
  if (nrow(out) > 0) {
    message(sprintf("  %d: %d %s utilities (long form)", yr, nrow(out), state_abb))
  }
  out
})

message("\n=== Parsing EIA-861 short form ===")
eia_short <- map_dfr(full_year_range, function(yr) {
  zip_file <- file.path(dir_eia_861, sprintf("f861%d.zip", yr))
  if (!file.exists(zip_file)) return(tibble())
  out <- tryCatch(
    parse_eia_861_short(zip_file, yr, state_abb),
    error = function(e) {
      warning(sprintf("Short-form parse failed for %d: %s", yr, e$message))
      tibble()
    }
  )
  if (nrow(out) > 0) {
    message(sprintf("  %d: %d %s utilities (short form)", yr, nrow(out), state_abb))
  }
  out
})

# Combine long + short, keeping long form when a utility reported both
eia_all_wi <- bind_rows(eia_long, eia_short) %>%
  arrange(utility_name, emissions_year, desc(data_source == "eia_861_long")) %>%
  group_by(utility_name, emissions_year) %>%
  slice(1) %>%
  ungroup()

# Restrict to in-scope WI utilities
wi_utility_elec_activity_eia861 <- eia_all_wi %>%
  filter(utility_name %in% wi_elec_utils_scope$utility_name) %>%
  left_join(
    wi_elec_utils_scope %>%
      distinct(utility_name, utility_type),
    by = "utility_name"
  ) %>%
  select(
    utility_name, utility_name_raw, utility_type, state, emissions_year,
    any_of(c(
      "residential", "commercial", "industrial", "transportation", "total",
      "residential_customers", "commercial_customers",
      "industrial_customers", "transportation_customers", "total_customers"
    )),
    unit_activity, data_source, eia_form
  ) %>%
  arrange(utility_name, emissions_year)

# --- QA summary --------------------------------------------------------------

message(sprintf(
  "\nWI EIA-861 activity table: %d utility-years across %d utilities, %d-%d",
  nrow(wi_utility_elec_activity_eia861),
  n_distinct(wi_utility_elec_activity_eia861$utility_name),
  min(wi_utility_elec_activity_eia861$emissions_year, na.rm = TRUE),
  max(wi_utility_elec_activity_eia861$emissions_year, na.rm = TRUE)
))

coverage <- wi_utility_elec_activity_eia861 %>%
  count(utility_name, data_source) %>%
  tidyr::pivot_wider(names_from = data_source, values_from = n, values_fill = 0L)
message("\nCoverage by utility x form:")
print(coverage)

# --- QA: check for partial (not just total-absence) coverage gaps -----------
# A utility can pass the total-absence check below (it has *some* matched
# years) while still silently missing most of its history if the EIA raw
# name format changed across years in a way the harmonization lookup doesn't
# capture (this is what happened with NSP-WI's pre-2012 filings). Flag any
# in-scope utility whose matched-year count is well below the
# best-covered utility's count.

scope_year_counts <- wi_utility_elec_activity_eia861 %>%
  count(utility_name, name = "n_years")

max_years <- max(scope_year_counts$n_years, na.rm = TRUE)

partial_gap_utilities <- wi_elec_utils_scope %>%
  distinct(utility_name) %>%
  left_join(scope_year_counts, by = "utility_name") %>%
  mutate(n_years = coalesce(n_years, 0L)) %>%
  filter(n_years > 0, n_years < max_years * 0.75) %>%
  pull(utility_name)

if (length(partial_gap_utilities) > 0) {
  message(sprintf(
    "\nUtilities with partial-coverage gaps (< 75%% of the best-covered utility's %d years): %s",
    max_years, paste(partial_gap_utilities, collapse = "; ")
  ))
}

missing_scope <- union(
  setdiff(wi_elec_utils_scope$utility_name, wi_utility_elec_activity_eia861$utility_name),
  partial_gap_utilities
)
if (length(missing_scope) > 0) {
  warning(sprintf(
    "In-scope utilities with missing or incomplete EIA-861 coverage: %s",
    paste(missing_scope, collapse = "; ")
  ))

  # --- diagnostic: surface near-matches to help identify the correct raw name --
  # EIA-861 naming for small co-ops is inconsistent across years (hyphenation,
  # abbreviations, "Inc"/"Coop" suffixes, occasional filing under a parent
  # G&T's name). Rather than guess blindly, search all parsed WI raw names
  # (pre-scope-filter) for the missing utility's distinctive words so the
  # correct eia_name_lookup_wi entry can be added.
  generic_utility_words <- c(
    "company", "co", "corporation", "corp", "cooperative", "coop",
    "electric", "power", "light", "utility", "utilities", "services",
    "service", "inc", "incorporated", "llc", "assn", "association",
    "municipal", "of", "the"
  )

  message("\n--- Diagnostic: searching all parsed WI utility names for near-matches ---")
  for (missing_name in missing_scope) {
    tokens <- str_split(missing_name, "[^A-Za-z]+")[[1]]
    tokens <- tokens[!tolower(tokens) %in% tolower(generic_utility_words)]
    tokens <- tokens[nchar(tokens) > 2]

    if (length(tokens) == 0) next

    pattern <- paste(tokens, collapse = "|")
    candidates <- eia_all_wi %>%
      filter(str_detect(utility_name_raw, regex(pattern, ignore_case = TRUE))) %>%
      distinct(utility_name_raw, data_source, emissions_year) %>%
      arrange(utility_name_raw, emissions_year)

    if (nrow(candidates) > 0) {
      message(sprintf(
        "\nNear-matches for '%s' (search tokens: %s):",
        missing_name, paste(tokens, collapse = ", ")
      ))
      print(candidates, n = Inf)
    } else {
      message(sprintf(
        paste0(
          "\nNo near-matches found for '%s' in any parsed WI EIA-861 year. ",
          "This utility may not file EIA-861 at all (small co-ops sometimes ",
          "report only through a parent G&T cooperative), or may not appear ",
          "in the state == 'WI' filter for its own filings."
        ),
        missing_name
      ))
    }
  }
}

# --- write outputs -----------------------------------------------------------

write_rds(
  wi_utility_elec_activity_eia861,
  here("_energy", "data", "WI_utility_elec_activity_eia861.RDS")
)

