source("R/_load_pkgs.R")
library(readxl)


#Note about co-op utilities -- electric eco-ops don't report to the state of Wisconsin, and two of four are missing data in/for EIA-861 (The Annual Electric Power Industry Report). For these, we estimate activity based on customer/account numbers reported by the utilities.

# 1) St Croix Electric Cooperative: 11,637 customer accounts on 2021 annual report https://scecnet.net/elm-2022
# 2) Pierce-Pepin Electric Cooperative Services: 7,859 customers accounts (as of 12/31/2022, year-end 2021 numbers were not available). https://piercepepin.coop/ppcs-quick-facts
#Dunn County Electric Coop and Polk-Burnett Electric Coop -- activity data provided to federal government at state level (i.e., all electricity delivered in WI) allocated to counties in study area weighted by population
#source: US Energy Information Administration, Annual Electric Power Industry Report, Form EIA-861 detailed data files (Sales to Ultiamte Customers) -- https://www.eia.gov/electricity/data/eia861/


#fullElecUtilityServiceAreas_CensusBlockSums.shp is a file processed in ArcGIS Pro that followed the same steps as the R code listed at the bottom of this code chunk (which wouldn't run on my machine due to performance limitations) -- i.e., taking the centroids of census blocks and summing up the population of blocks whose centroids intersect/are within the utility service area polygons
fullElecUtilityServiceAreas_CensusBlockSums <- st_read(
  here("_energy", "data-raw",
  "wi_utility_reporting", "fullElecUtilityServiceAreas_CensusBlockSums.shp")
) 

#same as above, but JUST for the portions of utility service area that fall within our two-county Wisconsin study area; this file will enable a proportional allocation of statewide energy activity data (represented by the entire service areas) to our two counties of interest
WIutilities_in_scope_CensusBlockSums <- st_read(
  here("_energy", "data-raw",
       "wi_utility_reporting", "WIutilities_in_scope_CensusBlockSums.shp")
) 

# The following code manually inputs data on electricity delivered, total customer count, and customer count by county where this information is known. The end result is a dataset mixing real, reported numbers and modeled numbers that attempts to link a certain amount of electricity delivered to the 12 county-utility pairs (7 utilities, 2 counties, 2 utilities operate in only one county) present in our two county study area within WI. 

#start with spatial file of service areas for just the in-scope utilities
combined_wi_elecUtil_activityData <- st_drop_geometry(WIutilities_in_scope_CensusBlockSums) %>%
  #drop spatial attributes to facilitate use of dplyr utilities
  rename(utility_name = utlty_n, 
         countyUtilityPop = sum_value, #sum_value is the name generated by ArcGIS Pro's Summarize Within geoprocessing utility, which was used to create this data
         county_name = cnty_nm) %>%
  #first, prepare county-level allocations of statewide activity data
  left_join(st_drop_geometry(fullElecUtilityServiceAreas_CensusBlockSums) %>%
              rename(utility_name = utlty_nm_x, 
                     totalUtilityPop = sum_value),
            by = "utility_name") %>%
  select(utility_name, county_name, countyUtilityPop, totalUtilityPop) %>%
  mutate(propUtilityPopInCounty = countyUtilityPop / totalUtilityPop) %>%
  mutate(
    #input total mWh for the 5 out of 7 utilities we have this info for
    util_Total_mWh = case_when(
      utility_name == "Dunn Energy Cooperative" ~ 220809, #EIA-861 long form
      utility_name == "Polk-Burnett Electric Cooperative" ~ 241590, #EIA-861 long form
      utility_name == "New Richmond Municipal Electric Utility" ~ 102201.827, #WI reporting
      utility_name == "River Falls Municipal Utility" ~ 128159.282, #WI reporting
      utility_name == "Northern States Power Company-Wisconsin" ~ 6788131, #WI reporting
      utility_name == "St Croix Electric Cooperative" ~ 202641, #EIA-861 short form
      utility_name == "Pierce-Pepin Electric Cooperative Services" ~ 121060 #EIA-861 short form
    ),
    #input total customer count for the 7 utilities (we have info for all)
    utility_TotalCustomerCount = case_when(
      utility_name == "Dunn Energy Cooperative" ~ 10270,
      utility_name == "Polk-Burnett Electric Cooperative" ~ 21303,
      utility_name == "St Croix Electric Cooperative" ~ 11386, #EIA-861 short form
      utility_name == "Pierce-Pepin Electric Cooperative Services" ~ 7795, #EIA-861 short form
      utility_name == "Northern States Power Company-Wisconsin" ~ 266071,
      utility_name == "River Falls Municipal Utility" ~ 7038,
      utility_name == "New Richmond Municipal Electric Utility" ~ 5333
    ),
    #input county-specific customer coutns -- we have this for 3 of 7 utilities
    utilityCustomer_county = case_when(
      utility_name == "New Richmond Municipal Electric Utility" ~ 5333,
      utility_name == "Northern States Power Company-Wisconsin" 
      & county_name == "Pierce" ~ 7489,
      utility_name == "Northern States Power Company-Wisconsin" 
      & county_name == "St. Croix" ~ 24850,  
      utility_name == "River Falls Municipal Utility" 
      & county_name == "Pierce" ~ 4901,
      utility_name == "River Falls Municipal Utility" 
      & county_name == "St. Croix" ~ 2137
    ),
    #calculate the proportion of a utility's total customers that fall within each
    #county it operates within across our two county study area
    propCustomerAccountsInCounty = 
      utilityCustomer_county / utility_TotalCustomerCount,
    #estimate the number of customer accounts within the service territory included
    #within our two county study area when not reported directly by the utility
    #use Census population in study area service area / whole service area (propUtilityPopInCounty)
    #and multyiply by total customer count to estimate accounts in study area
    EST_CustomerAccountsInCounty = 
      ifelse(!is.na(utilityCustomer_county), 
             NA, 
             round(propUtilityPopInCounty * utility_TotalCustomerCount)),
    EST_propCustomerAccountsInCounty = 
      ifelse(!is.na(utilityCustomer_county), 
             NA, 
             EST_CustomerAccountsInCounty / utility_TotalCustomerCount),
    utilityCounty_mWh = 
      ifelse(!is.na(utilityCustomer_county), 
             util_Total_mWh * (propCustomerAccountsInCounty), 
             NA),
    mWh_perCustomerAccount = 
      ifelse(!is.na(EST_CustomerAccountsInCounty),
             NA,
             util_Total_mWh / utility_TotalCustomerCount),
    EST_utilityCounty_mWh = 
      ifelse(is.na(EST_CustomerAccountsInCounty),
             NA,
             EST_propCustomerAccountsInCounty * util_Total_mWh),
    EST_mWh_perCustomerAccount = 
      ifelse(is.na(EST_CustomerAccountsInCounty),
             NA,
             EST_utilityCounty_mWh / EST_CustomerAccountsInCounty)
  )


# Calculate weights to generate modeled mWh per account and for the entire utility county, where this info is not reported
# Originally written to estimate activity for St. Croix Electric Coop and Pierce Pepin Electric Cooperative Services
# Modeled numbers no longer necessary, but code is being saved to retain coalesced_utilityCounty_mWh
total_weighted_mWh <- sum(coalesce(combined_wi_elecUtil_activityData$mWh_perCustomerAccount, combined_wi_elecUtil_activityData$EST_mWh_perCustomerAccount) * coalesce(combined_wi_elecUtil_activityData$utilityCustomer_county, combined_wi_elecUtil_activityData$EST_CustomerAccountsInCounty), na.rm = TRUE)
total_account_weight <- sum(coalesce(combined_wi_elecUtil_activityData$utilityCustomer_county, combined_wi_elecUtil_activityData$EST_CustomerAccountsInCounty), na.rm = TRUE)
weighted_mWh_perAccount <- total_weighted_mWh / total_account_weight

# Impute this weighted mean into rows where both mWh_perCustomerAccount and EST_mWh_perCustomerAccount are null
combined_wi_elecUtil_activityData <- combined_wi_elecUtil_activityData %>%
  mutate(
    modeled_mWH_perCustomerAccount = ifelse(
      is.na(mWh_perCustomerAccount) & is.na(EST_mWh_perCustomerAccount),
      weighted_mWh_perAccount,
      NA
    ),
    modeled_utilityCounty_mWh = modeled_mWH_perCustomerAccount * EST_CustomerAccountsInCounty,
    coalesced_utilityCounty_mWh = coalesce(utilityCounty_mWh,
                                           EST_utilityCounty_mWh,
                                           modeled_utilityCounty_mWh)

  )


# Load eGRID Total Output Emission Rates (lb/MWh) for the MROW subregion (which covers our study area) from https://www.epa.gov/egrid/summary-data 
# figures in lbs./mWh -- CO2: 995.8;	CH4: 0.107; N2O: 0.015 --> 1003.1 CO2e total
eGRID_MROW_emissionsFactor_CO2 <- 995.8
eGRID_MROW_emissionsFactor_CH4 <- 0.107
eGRID_MROW_emissionsFactor_N2O <- 0.015


# Assuming each row in wi_electricity_data represents a utility's electricity delivery in a county, process and merge data
processed_wi_elecUtil_activityData <- combined_wi_elecUtil_activityData %>%
  mutate(CO2_emissions = coalesced_utilityCounty_mWh * eGRID_MROW_emissionsFactor_CO2,
         CH4_emissions = coalesced_utilityCounty_mWh * eGRID_MROW_emissionsFactor_CH4,
         N2O_emissions = coalesced_utilityCounty_mWh * eGRID_MROW_emissionsFactor_N2O)

WIcounty_level_electricity_emissions <- processed_wi_elecUtil_activityData %>%
  group_by(county_name) %>%
  summarise(total_CO2_emissions_lbs = sum(CO2_emissions, na.rm = TRUE),
            total_CO2_emissions_tons = total_CO2_emissions_lbs / 2000,
            total_CH4_emissions_lbs = sum(CH4_emissions, na.rm = TRUE),
            total_CH4_emissions_tons = total_CH4_emissions_lbs / 2000,
            total_N2O_emissions_lbs = sum(N2O_emissions, na.rm = TRUE),
            total_N2O_emissions_tons = total_N2O_emissions_lbs / 2000,
            total_CO2e_emissions_lbs = sum(CO2_emissions + 
                                             CH4_emissions + 
                                             N2O_emissions, 
                                           na.rm = TRUE),
            total_CO2e_emissions_tons = total_CO2e_emissions_lbs / 2000) %>%
  mutate(state = "WI",
         sector = "Electricity",
         year = 2021)


write_rds(processed_wi_elecUtil_activityData, here("_energy", "data", "wisconsin_elecUtils_ActivityAndEmissions.RDS"))
write_rds(WIcounty_level_electricity_emissions, here("_energy", "data", "wisconsin_county_ElecEmissions.RDS"))

# USE THE FOLLOWING CODE TO GET CENSUS BLOCKS FOR WISCONSIN TO IDENTIFY POPULATIONS IN UTILITY SERVICE AREAS

#get block-level populations for whole of Wisconsin, and allocate population to the whole of service areas served by utilities
#wisconsinPopBlocks <- get_decennial(
#  state = "WI",
#  geography = "block",
#  variables = "P1_001N",
#  sumfile = "pl",
#  geometry = TRUE,
#  year = 2020
#) %>% 
#harmonize to Wisconsin state-level data CRS
#  st_transform(st_crs(fullServiceArea_inScopeUtilities_WI))

#The following code threw an error due to an overage of memory, so I shifted to ArcGIS Pro to complete this spatial data task.
#utilityPopTotals <- fullServiceArea_inScopeUtilities_WI %>%
#  st_join(st_centroid(wisconsinPopBlocks), 
#          join = st_intersects,
#          left = TRUE) %>%
#  group_by(utlty_nm_x) %>%
#  summarize(total_pop_served = sum(value)) %>%
#  ungroup()
