# Stationary Energy
```{r  include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  # results = "hide",
  fig.pos = "H",
  out.width = "100%",
  dpi = 300
)


knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```
```{r, include=FALSE}
source(file.path(here::here(), "R/_quarto_helpers.R"))
source(file.path(here::here(), "R/_load_pkgs.R"))
source(file.path(here::here(), "R/_plotting_helpers.R"))
hookaddcap()
county_emissions <- readRDS(file.path(here::here(), "_meta/data/cprg_county_emissions.RDS"))
```

## Introduction



```{r fig-energy-county-emissions}
#| fig-cap: "Energy county emissions"
#| out-width: "95%"
fig_energy_county_emissions <- plot_county_sector_emissions(county_emissions,
                             .sector = "Energy",
                             .plotly_source ="fig-energy-county-emissions")
fig_energy_county_emissions
```


```{r fig-energy-emissions-by-category}
#| fig-cap: "Energy county emissions by category"
#| out-width: "95%"
fig_energy_emissions_by_category <- plot_county_emissions(
  county_emissions = county_emissions,
  .sector = "Energy",
  .plotly_source = "fig-energy-emissions-by-category"
)
fig_energy_emissions_by_category
```

{{< include _energy_electricity_emissions.qmd >}}

{{< include _energy_natural_gas_emissions.qmd >}}




```{r echo=FALSE}
caption_index <- readRDS(file.path(here::here(), "caption_index.RDS"))
caption_index <- as.character(as.numeric(caption_index) + 1) %>% stringr::str_pad(width = 2, side = "left", pad = "0")
saveCap(paste0("cap-", caption_index))
saveRDS(caption_index, file.path(here::here(), "caption_index.RDS"))
```
{{< pagebreak >}}
