## MPCA SCORE UPDATE {#sec-mpca-score-update}

```{r}
source(file.path(here::here(), "R/_quarto_helpers.R"))
source(file.path(here::here(), "R/_load_pkgs.R"))
source(file.path(here::here(), "R/_plotting_helpers.R"))
# pull data here
mpca_score <- readRDS(file.path(here::here(), "_waste/data-raw/mpca_score_allyrs.RDS")) %>%
  mutate(Method = ifelse(Method == "WTE", "Waste-to-Energy", Method)) %>%
  mutate(Method = factor(Method,
    levels = c(
      "Waste-to-Energy",
      "Organics",
      "Recycling",
      "Landfill",
      "MSW Compost",
      "Onsite"
    ),
    ordered = TRUE
  ))
mpca_score_meta <- readRDS(file.path(here::here(), "_waste/data/mpca_score_meta.RDS"))
cprg_county <- readRDS(file.path(here::here(), "_meta/data/cprg_county.RDS"))
cprg_pop <- readRDS(file.path(here::here(), "_meta/data/cprg_population.RDS"))
hookaddcap()
```

```{r}
# graph mpca totals by county(cat) by year
mpca_waste_sums <- mpca_score %>%
  group_by(County, Year) %>%
  summarize(total_waste = sum(Tons))

ggplot(mpca_waste_sums) +
  geom_line(aes(Year, total_waste, color = County))

mpca_score %>%
  group_by(Method, Year) %>%
  summarize(total_waste = sum(Tons)) %>%
  ggplot() +
  geom_line(aes(Year, total_waste, color = Method))
```


```{r echo=FALSE, eval=FALSE}
caption_index <- readRDS(file.path(here::here(), "caption_index.RDS"))
caption_index <- as.character(as.numeric(caption_index) + 1) %>% stringr::str_pad(width = 2, side = "left", pad = "0")
saveCap(paste0("cap-", caption_index))
saveRDS(caption_index, file.path(here::here(), "caption_index.RDS"))
```
