# Data sources {#sec-data-transportation}

```{r  include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.pos = "H",
  out.width = "100%",
  dpi = 300
)

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```
```{r include=FALSE}
source(file.path(here::here(), "R/_quarto_helpers.R"))
source(file.path(here::here(), "R/_load_pkgs.R"))
source(file.path(here::here(), "R/_plotting_helpers.R"))

cprg_census_county_population <- readRDS(file.path(here::here(), "_meta/data/census_county_population.RDS")) %>%
  filter(cprg_area == TRUE) %>%
  mutate(population_year = as.numeric(population_year))
county_emissions <- readRDS(file.path(here::here(), "_meta/data/cprg_county_emissions.RDS"))

onroad_emissions <- readRDS(file.path(here::here(), "_transportation/data/onroad_emissions.RDS")) %>%
  rename(value_emissions = emissions_metric_tons_co2e)

county_inventory_forecast_emissions <- readRDS(file.path(here::here(), "_transportation/data/county_inventory_forecast_emissions.RDS")) %>%
  rowwise() %>%
  mutate(rounded_tons = round_emissions_metric_tons_co2e(emissions_metric_tons_co2e))


transportation_max_year <- onroad_emissions %>%
  filter(emissions_year == max(emissions_year)) %>%
  extract2("emissions_year") %>%
  unique()

transportation_min_year <- onroad_emissions %>%
  filter(emissions_year == min(emissions_year)) %>%
  extract2("emissions_year") %>%
  unique()

modes_included <-
  stringr::str_split(onroad_emissions$vehicle_types_included, pattern = ", ", simplify = TRUE)[, 1] %>%
  unique() %>%
  stringr::str_to_lower()

mndot_vmt_ctu_gap_filled <- readRDS(file.path(here::here(), "_transportation/data/mndot_vmt_ctu_gap_filled.RDS"))

hookaddcap()
```


<!-- {{< include data_aviation.qmd >}} -->

{{< include data_epa_emissions.qmd >}}

<!-- {{< include data_streetlight.qmd >}} -->

{{< include data_state_dot.qmd >}}

<!-- {{< include data_epa_moves.qmd >}} -->

<!-- {{< include data_tbi.qmd >}} -->

{{< include data_regional_travel_demand_model.qmd >}}

{{< include data_original_analysis.qmd >}}


```{r echo=FALSE}
caption_index <- readRDS(file.path(here::here(), "caption_index.RDS"))
caption_index <- as.character(as.numeric(caption_index) + 1) %>% stringr::str_pad(width = 2, side = "left", pad = "0")
saveCap(paste0("cap-", caption_index))
saveRDS(caption_index, file.path(here::here(), "caption_index.RDS"))
```

{{< pagebreak >}}

