# Additional resources
```{r  include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.pos = "H",
  out.width = "100%",
  dpi = 300
)


knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```
```{r, include=FALSE}
source(file.path(here::here(), "R/_quarto_helpers.R"))
source(file.path(here::here(), "R/_load_pkgs.R"))
source(file.path(here::here(), "R/_plotting_helpers.R"))
hookaddcap()
```

## Climate Pollution Reduction Grants (CPRG) 

- Climate Pollution Reduction Grants [EPA site](https://www.epa.gov/inflation-reduction-act/climate-pollution-reduction-grants) and [SAM.gov](https://sam.gov/fal/6ccff3d73583450ba88ecef4bee21212/view)
- Funding information for this project on [USASpending.gov](https://www.usaspending.gov/award/ASST_NON_00E03476_6800)
- Minnesota statewide Priority Climate Action Plan (PCAP) [engagement page](https://engage.eqb.state.mn.us/climate-priorities)

## Energy

- U.S. Energy Information Administration (EIA) Glossary, available on their [website](https://www.eia.gov/tools/glossary/).

```{r echo=FALSE}
caption_index <- readRDS(file.path(here::here(), "caption_index.RDS"))
caption_index <- as.character(as.numeric(caption_index) + 1) %>% stringr::str_pad(width = 2, side = "left", pad = "0")
saveCap(paste0("cap-", caption_index))
saveRDS(caption_index, file.path(here::here(), "caption_index.RDS"))
```
{{< pagebreak >}}
