# Supplementary tables
```{r  include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.pos = "H",
  out.width = "100%",
  dpi = 300
)


knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```
```{r, include=FALSE}
source(file.path(here::here(), "R/_quarto_helpers.R"))
source(file.path(here::here(), "R/_load_pkgs.R"))
hookaddcap()
```
## Acronyms

```{r tbl-acroynms}
#| tbl-cap: "Acronyms"
#| out-width: "95%"
read.csv(file.path(here::here(), "_meta/data-raw/acronyms.csv")) %>%
  gt() %>%
  gt::opt_row_striping() %>%
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_column_labels()
  ) %>%
  gt::as_raw_html()
```


## Data Quality

```{r tbl-quality-rank}
#| tbl-cap: "Data source quality ranking"
#| out-width: "95%"
tibble::tribble(
  ~"Quality Rank", ~"Source Type",
  "Highest", "Federal, state, and local government agencies",
  "Second", "Consultant reports for state and local government agencies",
  "Third", "NGO studies; peer-reviewed journal articles; trade journal articles; conference proceedings",
  "Fourth", "Conference proceedings and other trade literature: non-peer-reviewed",
  "Fifth", "Individual estimates (e.g., via personal communication with vendors)"
) %>%
  gt() %>%
  gt::opt_row_striping() %>%
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_column_labels()
  ) %>%
  gt::as_raw_html()
```
```{r echo=FALSE}
caption_index <- readRDS(file.path(here::here(), "caption_index.RDS"))
caption_index <- as.character(as.numeric(caption_index) + 1) %>% stringr::str_pad(width = 2, side = "left", pad = "0")
saveCap(paste0("cap-", caption_index))
saveRDS(caption_index, file.path(here::here(), "caption_index.RDS"))
```
{{< pagebreak >}}
